// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtqfkhhcovnwnantrcjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0cWZraGhjb3Zud25hbnRyY2prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTg1NzYsImV4cCI6MjA3NDQ3NDU3Nn0.wZ_K760dHiY1n7_--qhQnD9v8JrjAiQIvyXSDRl3o8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});